"""Pass 4: fix remaining unaccented words in Resultados figure captions + scan."""
import re
QMD = 'TESE_CorePAM_v0.2.qmd'
t = open(QMD, encoding='utf-8').read()

more = {
    'associacao': 'associação',
    'Associacao': 'Associação',
    'associacoes': 'associações',
    'Dicotomizacao': 'Dicotomização',
    'dicotomizacao': 'dicotomização',
    'iteracoes': 'iterações',
    'iteracao': 'iteração',
    'catastrofica': 'catastrófica',
    'catastrofico': 'catastrófico',
    'Separacao': 'Separação',
    'separacao': 'separação',
    'derivacao': 'derivação',
    'Derivacao': 'Derivação',
    'validacao': 'validação',
    'Validacao': 'Validação',
    'validacoes': 'validações',
    'calibracao': 'calibração',
    'Calibracao': 'Calibração',
    'estratificacao': 'estratificação',
    'Estratificacao': 'Estratificação',
    'comparacao': 'comparação',
    'Comparacao': 'Comparação',
    'comparacoes': 'comparações',
    'estimacao': 'estimação',
    'Estimacao': 'Estimação',
    'observacao': 'observação',
    'observacoes': 'observações',
    'distribuicao': 'distribuição',
    'Distribuicao': 'Distribuição',
    'distribuicoes': 'distribuições',
    'selecao': 'seleção',
    'Selecao': 'Seleção',
    'regressao': 'regressão',
    'Regressao': 'Regressão',
    'regressoes': 'regressões',
    'classificacao': 'classificação',
    'Classificacao': 'Classificação',
    'discriminacao': 'discriminação',
    'Discriminacao': 'Discriminação',
    'avaliacao': 'avaliação',
    'Avaliacao': 'Avaliação',
    'avaliacoes': 'avaliações',
    'reproducibilidade': 'reprodutibilidade',
    'Reproducibilidade': 'Reprodutibilidade',
    'inferencia': 'inferência',
    'Inferencia': 'Inferência',
    'inferencias': 'inferências',
    'predicoes': 'predições',
    'tecnica': 'técnica',
    'tecnicas': 'técnicas',
    'tecnico': 'técnico',
    'tecnicos': 'técnicos',
    'medico': 'médico',
    'medicos': 'médicos',
    'medica': 'médica',
    'medicas': 'médicas',
    'clinica': 'clínica',
    'clinico': 'clínico',
    'clinicas': 'clínicas',
    'clinicos': 'clínicos',
    'prognostica': 'prognóstica',
    'prognostico': 'prognóstico',
    'prognosticas': 'prognósticas',
    'prognosticos': 'prognósticos',
    'diagnostica': 'diagnóstica',
    'diagnostico': 'diagnóstico',
    'diagnosticas': 'diagnósticas',
    'diagnosticos': 'diagnósticos',
    'analise': 'análise',
    'analises': 'análises',
    'ultimo': 'último',
    'ultima': 'última',
    'ultimos': 'últimos',
    'ultimas': 'últimas',
    'pratica': 'prática',
    'praticas': 'práticas',
    'pratico': 'prático',
    'praticos': 'práticos',
    'numero': 'número',
    'numeros': 'números',
    'metodologia': 'metodologia',  # OK
    'metodologias': 'metodologias',  # OK
    'metodo': 'método',
    'metodos': 'métodos',
    'criterio': 'critério',
    'criterios': 'critérios',
    'historia': 'história',
    'historico': 'histórico',
    'historica': 'histórica',
    'historicos': 'históricos',
    'historicas': 'históricas',
    'especifica': 'específica',
    'especifico': 'específico',
    'especificas': 'específicas',
    'especificos': 'específicos',
    'especificamente': 'especificamente',
    'especificidade': 'especificidade',  # OK
    'sensibilidade': 'sensibilidade',  # OK
    'proprio': 'próprio',
    'propria': 'própria',
    'proprios': 'próprios',
    'proprias': 'próprias',
    'proximo': 'próximo',
    'proxima': 'próxima',
    'proximos': 'próximos',
    'proximas': 'próximas',
    'referencia': 'referência',
    'referencias': 'referências',
    'consequencia': 'consequência',
    'consequencias': 'consequências',
    'evidencia': 'evidência',
    'evidencias': 'evidências',
    'experiencia': 'experiência',
    'experiencias': 'experiências',
    'estrategia': 'estratégia',
    'estrategias': 'estratégias',
    'estrategico': 'estratégico',
    'estrategica': 'estratégica',
    'categoria': 'categoria',  # OK
    'categorias': 'categorias',  # OK
    'viavel': 'viável',
    'viaveis': 'viáveis',
    'inviavel': 'inviável',
    'disponivel': 'disponível',
    'disponiveis': 'disponíveis',
    'plausivel': 'plausível',
    'plausiveis': 'plausíveis',
    'compativel': 'compatível',
    'compativeis': 'compatíveis',
    'incompativel': 'incompatível',
    'responsavel': 'responsável',
    'responsaveis': 'responsáveis',
    'util': 'útil',
    'uteis': 'úteis',
    'dificil': 'difícil',
    'dificeis': 'difíceis',
    'facil': 'fácil',
    'faceis': 'fáceis',
    'possivel': 'possível',
    'possiveis': 'possíveis',
    'impossivel': 'impossível',
    'impossiveis': 'impossíveis',
    'niveis': 'níveis',
    'nivel': 'nível',
    'tambem': 'também',
    'atraves': 'através',
    'porem': 'porém',
    'alem': 'além',
    'apos': 'após',
    'ambito': 'âmbito',
    'enfase': 'ênfase',
    'fenotipo': 'fenótipo',
    'fenotipos': 'fenótipos',
    'genotipo': 'genótipo',
    'genotipos': 'genótipos',
    'heterogeneo': 'heterogêneo',
    'heterogenea': 'heterogênea',
    'heterogeneos': 'heterogêneos',
    'heterogeneas': 'heterogêneas',
    'homogeneo': 'homogêneo',
    'homogenea': 'homogênea',
}
for k, v in more.items():
    if k != v:
        p = re.compile(r'(?<!\w)' + re.escape(k) + r'(?!\w)')
        t = p.sub(v, t)

open(QMD, 'w', encoding='utf-8').write(t)
print('Pass 4 done. size:', len(t))
